# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python image with uv pre-installed
FROM ghcr.io/astral-sh/uv:python3.13-alpine AS uv

# Set working directory
WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy pyproject.toml, lock file, and README for dependencies
COPY pyproject.toml uv.lock README.md ./

# Install the project's dependencies
RUN uv sync --frozen --no-install-project --no-dev --no-editable

# Add the rest of the project source code and install it
ADD src /app/src

# Sync and install the project
RUN uv sync --frozen --no-dev --no-editable

FROM python:3.13-alpine

# Upgrade system packages to fix known vulnerabilities (e.g., zlib CVE)
RUN apk upgrade --no-cache

# Set working directory
WORKDIR /app

# Copy virtual environment from the builder
COPY --from=uv /app/.venv /app/.venv

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

# Expose port for SSE transport
EXPOSE 8000

# Define the entry point
ENTRYPOINT ["mcp-server-bigquery"]

# Default to SSE transport on port 8000
CMD ["--transport", "sse", "--port", "8000"]
